// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  deckId: __t.string(),
  stage: __t.string(),
  title: __t.string(),
  lens: __t.string(),
  imagePath: __t.string(),
  altText: __t.string(),
  provocation: __t.string(),
  tags: __t.string(),
};
