// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  roomId: __t.u64().primaryKey().name("room_id"),
  audience: __t.string(),
  valuePromise: __t.string().name("value_promise"),
  channel: __t.string(),
  callToAction: __t.string().name("call_to_action"),
  investment: __t.u32(),
  responseTitle: __t.string().name("response_title"),
  responseDescription: __t.string().name("response_description"),
  baseMultiplier: __t.u32().name("base_multiplier"),
  matched: __t.bool(),
  effectiveMultiplier: __t.u32().name("effective_multiplier"),
  committed: __t.bool(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
