// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  roomId: __t.u64().primaryKey().name("room_id"),
  successSignal: __t.string().name("success_signal"),
  outcome: __t.string(),
  readinessBonus: __t.u32().name("readiness_bonus"),
  decision: __t.string(),
  revision: __t.string(),
  resolved: __t.bool(),
  completed: __t.bool(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
