// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  roomId: __t.u64().primaryKey().name("room_id"),
  feedbackTitle: __t.string().name("feedback_title"),
  feedbackDescription: __t.string().name("feedback_description"),
  optionA: __t.string().name("option_a"),
  optionADescription: __t.string().name("option_a_description"),
  optionALearning: __t.string().name("option_a_learning"),
  optionB: __t.string().name("option_b"),
  optionBDescription: __t.string().name("option_b_description"),
  optionBLearning: __t.string().name("option_b_learning"),
  optionC: __t.string().name("option_c"),
  optionCDescription: __t.string().name("option_c_description"),
  optionCLearning: __t.string().name("option_c_learning"),
  decision: __t.string(),
  learning: __t.string(),
  completed: __t.bool(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
