// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  roomId: __t.u64().primaryKey().name("room_id"),
  challengeKey: __t.string().name("challenge_key"),
  challengeTitle: __t.string().name("challenge_title"),
  challengeDescription: __t.string().name("challenge_description"),
  artifactKind: __t.string().name("artifact_kind"),
  artifactData: __t.string().name("artifact_data"),
  caption: __t.string(),
  durationSeconds: __t.u32().name("duration_seconds"),
  investment: __t.u32(),
  creativePoints: __t.u32().name("creative_points"),
  committed: __t.bool(),
  startedAt: __t.timestamp().name("started_at"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
