// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { t as __t } from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  roomId: __t.u64().name("room_id"),
  authorIdentity: __t.identity().name("author_identity"),
  color: __t.string(),
  points: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
