// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  stage: __t.string(),
  playerIdentity: __t.identity().name("player_identity"),
  actionKey: __t.string().name("action_key"),
  actionTitle: __t.string().name("action_title"),
  actionPrompt: __t.string().name("action_prompt"),
  actionPlaceholder: __t.string().name("action_placeholder"),
  position: __t.u8(),
  createdAt: __t.timestamp().name("created_at"),
});
