// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  roomId: __t.u64().primaryKey().name("room_id"),
  initialBalance: __t.u32().name("initial_balance"),
  balance: __t.u32(),
  reservedBalance: __t.u32().name("reserved_balance"),
  seed: __t.u32(),
  nextSequence: __t.u32().name("next_sequence"),
  fundingStage: __t.string().name("funding_stage"),
  fundingValue: __t.u32().name("funding_value"),
  fundingTitle: __t.string().name("funding_title"),
  fundingDescription: __t.string().name("funding_description"),
  fundingRevealed: __t.bool().name("funding_revealed"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
