// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  stage: __t.string(),
  headline: __t.string(),
  body: __t.string(),
  optionsJson: __t.string().name("options_json"),
  selectedKey: __t.string().name("selected_key"),
  selectedLearning: __t.string().name("selected_learning"),
  completed: __t.bool(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
