// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  authorIdentity: __t.identity().name("author_identity"),
  showing: __t.string(),
  targetUser: __t.string().name("target_user"),
  storyboardStep1: __t.string().name("storyboard_step_1"),
  storyboardStep2: __t.string().name("storyboard_step_2"),
  storyboardStep3: __t.string().name("storyboard_step_3"),
  hypothesis: __t.string(),
  resources: __t.string(),
  smallestVersion: __t.string().name("smallest_version"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
