// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  optionKey: __t.string().name("option_key"),
  title: __t.string(),
  description: __t.string(),
  cost: __t.u32(),
  impact: __t.string(),
  outcomeHeadline: __t.string().name("outcome_headline"),
  outcomeBody: __t.string().name("outcome_body"),
  question: __t.string(),
  selected: __t.bool(),
  createdAt: __t.timestamp().name("created_at"),
});
