// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  stage: __t.string(),
  delta: __t.i32(),
  balanceAfter: __t.u32().name("balance_after"),
  sequence: __t.u32(),
  reason: __t.string(),
  eventKey: __t.string().name("event_key"),
  label: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
