// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Contribution = __t.object("Contribution", {
  id: __t.u64(),
  roomId: __t.u64(),
  stage: __t.string(),
  authorIdentity: __t.identity(),
  kind: __t.string(),
  content: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Contribution = __Infer<typeof Contribution>;

export const Player = __t.object("Player", {
  id: __t.u64(),
  roomId: __t.u64(),
  identity: __t.identity(),
  displayName: __t.string(),
  avatarId: __t.string(),
  role: __t.string(),
  ready: __t.bool(),
  online: __t.bool(),
  points: __t.u32(),
  joinedAt: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

export const Profile = __t.object("Profile", {
  identity: __t.identity(),
  displayName: __t.option(__t.string()),
  avatarId: __t.option(__t.string()),
  online: __t.bool(),
  updatedAt: __t.timestamp(),
});
export type Profile = __Infer<typeof Profile>;

export const Room = __t.object("Room", {
  id: __t.u64(),
  code: __t.string(),
  ownerIdentity: __t.identity(),
  status: __t.string(),
  mode: __t.string(),
  currentStage: __t.string(),
  stageIndex: __t.u8(),
  round: __t.u32(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Room = __Infer<typeof Room>;
