// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Card = __t.object("Card", {
  id: __t.string(),
  stage: __t.string(),
  title: __t.string(),
  lens: __t.string(),
  imagePath: __t.string(),
  altText: __t.string(),
  provocation: __t.string(),
});
export type Card = __Infer<typeof Card>;

export const CardDraw = __t.object("CardDraw", {
  id: __t.u64(),
  roomId: __t.u64(),
  stage: __t.string(),
  cardId: __t.string(),
  drawnAt: __t.timestamp(),
});
export type CardDraw = __Infer<typeof CardDraw>;

export const Contribution = __t.object("Contribution", {
  id: __t.u64(),
  roomId: __t.u64(),
  stage: __t.string(),
  authorIdentity: __t.identity(),
  kind: __t.string(),
  content: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Contribution = __Infer<typeof Contribution>;

export const Decision = __t.object("Decision", {
  id: __t.u64(),
  roomId: __t.u64(),
  stage: __t.string(),
  selectedContributionId: __t.u64(),
  summary: __t.string(),
  totalVotes: __t.u32(),
  decidedAt: __t.timestamp(),
});
export type Decision = __Infer<typeof Decision>;

export const Journey = __t.object("Journey", {
  id: __t.u64(),
  roomId: __t.u64(),
  title: __t.string(),
  summary: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Journey = __Infer<typeof Journey>;

export const Player = __t.object("Player", {
  id: __t.u64(),
  roomId: __t.u64(),
  identity: __t.identity(),
  displayName: __t.string(),
  avatarId: __t.string(),
  role: __t.string(),
  ready: __t.bool(),
  online: __t.bool(),
  points: __t.u32(),
  joinedAt: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

export const Profile = __t.object("Profile", {
  identity: __t.identity(),
  displayName: __t.option(__t.string()),
  avatarId: __t.option(__t.string()),
  online: __t.bool(),
  updatedAt: __t.timestamp(),
});
export type Profile = __Infer<typeof Profile>;

export const Room = __t.object("Room", {
  id: __t.u64(),
  code: __t.string(),
  ownerIdentity: __t.identity(),
  status: __t.string(),
  mode: __t.string(),
  currentStage: __t.string(),
  stageIndex: __t.u8(),
  round: __t.u32(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Room = __Infer<typeof Room>;

export const StageSession = __t.object("StageSession", {
  id: __t.u64(),
  roomId: __t.u64(),
  stage: __t.string(),
  phase: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type StageSession = __Infer<typeof StageSession>;

export const Vote = __t.object("Vote", {
  id: __t.u64(),
  roomId: __t.u64(),
  stage: __t.string(),
  voterIdentity: __t.identity(),
  contributionId: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Vote = __Infer<typeof Vote>;
