// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AdvanceStageReducer from "../advance_stage_reducer";
import CreateRoomReducer from "../create_room_reducer";
import JoinRoomReducer from "../join_room_reducer";
import SetProfileReducer from "../set_profile_reducer";
import SetReadyReducer from "../set_ready_reducer";
import StartGameReducer from "../start_game_reducer";
import SubmitContributionReducer from "../submit_contribution_reducer";

export type AdvanceStageParams = __Infer<typeof AdvanceStageReducer>;
export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type SetProfileParams = __Infer<typeof SetProfileReducer>;
export type SetReadyParams = __Infer<typeof SetReadyReducer>;
export type StartGameParams = __Infer<typeof StartGameReducer>;
export type SubmitContributionParams = __Infer<typeof SubmitContributionReducer>;
