// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AdvanceStageReducer from "../advance_stage_reducer";
import CastVoteReducer from "../cast_vote_reducer";
import CreateRoomReducer from "../create_room_reducer";
import EndJourneyReducer from "../end_journey_reducer";
import FinishPrototypeActivityReducer from "../finish_prototype_activity_reducer";
import JoinRoomReducer from "../join_room_reducer";
import LeaveRoomReducer from "../leave_room_reducer";
import OpenVotingReducer from "../open_voting_reducer";
import RefreshRedrawnCardReducer from "../refresh_redrawn_card_reducer";
import ResolveStageReducer from "../resolve_stage_reducer";
import SetProfileReducer from "../set_profile_reducer";
import SetReadyReducer from "../set_ready_reducer";
import StartGameReducer from "../start_game_reducer";
import StartPrototypeActivityReducer from "../start_prototype_activity_reducer";
import SubmitContributionReducer from "../submit_contribution_reducer";
import SubmitPrototypeArtifactReducer from "../submit_prototype_artifact_reducer";
import UpdateJourneyReducer from "../update_journey_reducer";
import VoteCardChangeReducer from "../vote_card_change_reducer";
import VoteMarketingPlanReducer from "../vote_marketing_plan_reducer";
import VotePilotResponseReducer from "../vote_pilot_response_reducer";
import VotePrototypeExtensionReducer from "../vote_prototype_extension_reducer";
import VotePrototypeReadyReducer from "../vote_prototype_ready_reducer";

export type AdvanceStageParams = __Infer<typeof AdvanceStageReducer>;
export type CastVoteParams = __Infer<typeof CastVoteReducer>;
export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type EndJourneyParams = __Infer<typeof EndJourneyReducer>;
export type FinishPrototypeActivityParams = __Infer<typeof FinishPrototypeActivityReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type OpenVotingParams = __Infer<typeof OpenVotingReducer>;
export type RefreshRedrawnCardParams = __Infer<typeof RefreshRedrawnCardReducer>;
export type ResolveStageParams = __Infer<typeof ResolveStageReducer>;
export type SetProfileParams = __Infer<typeof SetProfileReducer>;
export type SetReadyParams = __Infer<typeof SetReadyReducer>;
export type StartGameParams = __Infer<typeof StartGameReducer>;
export type StartPrototypeActivityParams = __Infer<typeof StartPrototypeActivityReducer>;
export type SubmitContributionParams = __Infer<typeof SubmitContributionReducer>;
export type SubmitPrototypeArtifactParams = __Infer<typeof SubmitPrototypeArtifactReducer>;
export type UpdateJourneyParams = __Infer<typeof UpdateJourneyReducer>;
export type VoteCardChangeParams = __Infer<typeof VoteCardChangeReducer>;
export type VoteMarketingPlanParams = __Infer<typeof VoteMarketingPlanReducer>;
export type VotePilotResponseParams = __Infer<typeof VotePilotResponseReducer>;
export type VotePrototypeExtensionParams = __Infer<typeof VotePrototypeExtensionReducer>;
export type VotePrototypeReadyParams = __Infer<typeof VotePrototypeReadyReducer>;

